---
title: test3
author: yo
date: '2021-02-02'
slug: []
categories: []
tags: []
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---


# Introducción

* a) Planteamiento del problema


* b) Objetivo del proyecto

```{r}

library(easypackages)

my_packages <- c("tidyverse", "lubridate", "readxl", "sf", "OpenStreetMap")

libraries(my_packages)

```




# Análisis exploratorio de datos



```{r}


data <- read_csv("denue_inegi_02_.csv", guess_max = 1000000)


db <- data %>%
  select(id, per_ocu, nombre_act, entidad, municipio, ageb, latitud, longitud, fecha_alta, codigo_act) %>%
  mutate(code = str_extract(string = as.character(codigo_act), pattern = "(\\d\\d)"),
         y = latitud,
         x = longitud,
         codigo_act = as.character(codigo_act)) %>%
  filter(municipio %in% c("Tijuana") & code %in% c("46") & per_ocu %in% c("6 a 10 personas")) %>%
  distinct(id, .keep_all = TRUE)
  
  


```



```{r}


db %>%
  mutate(sector = str_extract(string = codigo_act, pattern = "(\\d\\d\\d)")) %>%
  group_by(sector) %>%
  summarise(n = n()) %>% 
  mutate(sector = fct_recode(sector, 
                             "Industria Alimentaria" = "311",
                             "Industria de las bebidas y tabaco" = "312",
                             "Frabicación de insumos de textiles y acabados de textiles" = "313",
                             "Fabricación de productos textiles excepto prendas de vestir" = "314",
                             "Fabricación de prendas de vestir" = "315",
                             "Curtido y acabado de cuero y piel, fabricación de productos de cuero, piel y materiales sucedánios" = "316",
                             "Industria de la madera" = "321",
                             "Industria de papel" = "322",
                             "Impresión e industrias conexas" = "323",
                             "Fabricación de productos derivados del petroleo y del carbón" = "324",
                             "Industria quimica" = "325" ,
                             "Industria del plástico y del hule" = "326",
                             "Fabricación de productos a base de minerales no metálicos" = "327",
                             "Industrias metálicas básicas" = "328",
                             " Fabricación de productos metálicos" = "332",
                             "Fabricación de maquinaria y equipo" = "333",
                             "Fabricación de equipo de computación, comunicación, medición y de otros equipos, componentes y accesorios electrónicos" = "334",
                             "Fabricación de accesorios, aparatos eléctricos y equipo de generación de energía eléctrica" = "335",
                             "Fabricación de equipo de transporte" = "336",
                             "Fabricación de muebles, colchones y persianas" = "337",
                             "Otras industrias manufactureras" = "339", )) %>%
  ggplot(aes(x = reorder(sector, n), y = n, fill = factor(n))) + 
  geom_bar(stat = "identity") + 
  coord_flip() + 
  ggtitle("Numero de empresas en Industria Manufacturera en Tijuana") + 
  xlab("") + 
  ylab("Número de empresas") +
  theme_minimal() + 
  theme(legend.position = "none") 
  

```




# ANALISIS DE CONGLOMERADOS

Convertimos la tabla de datos a un objeto geoespacial

```{r message=FALSE}

map_dta <- db %>%
  mutate(sector = str_extract(string = codigo_act, pattern = "(\\d\\d)")) 


denue_sf <- st_as_sf(map_dta, coords = c("x", "y"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84")

plot(denue_sf)

```



```{r}


# GET PROJECTION

crs <- st_crs(denue_sf)

tj_map <- openmap(upperLeft = c(32.363723,-117.190132), 
                  lowerRight = c(32.590503,-116.640816),
                  type = "osm")


# REPROJECT THE MAP ACCORDING TO OUR POLYGONS

map.latlon <- openproj(tj_map, projection = crs$proj4string)


```


# Crea los clusters



```{r}

mdist <- st_distance(denue_sf)


hc <- hclust(as.dist(mdist), method = "complete")

d = 9000

denue_sf$clust <- cutree(hc, h = d)



```


# PRESENTAMOS ANALISIS DE CLUSTER GEOESPACIAL


A;LKSF;LASJDFL;KJAS;LKDFJA;LSKJF


```{r fig.width=15, fig.height=9, out.height='100%', out.width='100%'}


autoplot.OpenStreetMap(map.latlon) +
  geom_sf(data = denue_sf, inherit.aes = FALSE, mapping = aes(fill = clust))
  geom_polygon(data = denue_sf, aes(x = longitud, y = latitud), inherit.aes = FALSE)
  
  theme(axis.text.x = element_text(color = "#383838"),
        axis.text.y = element_text(color = "#383838"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.text = element_text(colour = "#383838"),
        legend.title = element_text(colour = "#383838"),
        legend.key = element_rect(colour = NA, fill = NA),
        legend.key.size = unit(1, "line"),
        legend.background = element_blank(),
        panel.grid.major = element_line(color = "#C0C0C0"),
        plot.title = element_text(vjust= 2.12, 
                                  colour="#5bb950",
                                  face="bold"),
        plot.caption = element_text(color = "#383838"),
        plot.subtitle = element_text(color = "#f6901e", face = "bold.italic")) + 
  guides(col = guide_legend(nrow = 16, byrow = TRUE))




```

